In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(5,)

In [5]:
b = np.array([[1], [2], [3], [4], [5]])

In [6]:
b.shape

(5, 1)

In [7]:
b

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [8]:
a = np.zeros((3, 3), dtype = int)

In [9]:
a.shape

(3, 3)

In [10]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
b = np.ones((3, 3))

In [12]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
c = np.full((3, 3), 5, dtype=float)

In [16]:
c

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [17]:
d = np.eye(4)

In [18]:
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
rn_mat = np.random.random((3, 3))

In [20]:
rn_mat

array([[0.92119856, 0.10662313, 0.32138713],
       [0.70588876, 0.5599578 , 0.18422243],
       [0.78375672, 0.52570701, 0.38548189]])

In [21]:
rn_mat[:2]

array([[0.92119856, 0.10662313, 0.32138713],
       [0.70588876, 0.5599578 , 0.18422243]])

In [22]:
rn_mat[: ,2]

array([0.32138713, 0.18422243, 0.38548189])

In [23]:
d.dtype

dtype('float64')

In [24]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [25]:
x + y

array([[ 6,  8],
       [10, 12]])

In [26]:
x - y

array([[-4, -4],
       [-4, -4]])

In [27]:
x*y

array([[ 5, 12],
       [21, 32]])

In [28]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [29]:
print(np.add(x, y))

[[ 6  8]
 [10 12]]


In [30]:
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]


In [31]:
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]


In [32]:
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [33]:
np.sqrt(144)

12.0

In [34]:
print(np.matmul(x, y))

[[19 22]
 [43 50]]


In [35]:
print(np.dot(x, y))

[[19 22]
 [43 50]]


In [36]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [37]:
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,4,5,6])

In [38]:
print(a.dot(b))
print(np.dot(a, b))

91
91


In [39]:
sum(a)

21

In [40]:
np.sum(a)

21

In [41]:
a

array([1, 2, 3, 4, 5, 6])

In [42]:
b

array([1, 2, 3, 4, 5, 6])

In [43]:
b = b**2

In [44]:
b

array([ 1,  4,  9, 16, 25, 36])

In [45]:
np.stack((a, b), axis = 1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [49]:
a = np.stack((a, b), axis = 0)

In [50]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 1,  4,  9, 16, 25, 36]])

In [51]:
a.T

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [52]:
a.reshape((6, 2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 1,  4],
       [ 9, 16],
       [25, 36]])

In [53]:
a.reshape((4, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  4,  9],
       [16, 25, 36]])

In [54]:
a.reshape((3, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  1,  4],
       [ 9, 16, 25, 36]])

In [55]:
a.reshape((-1, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  1,  4],
       [ 9, 16, 25, 36]])

In [56]:
a.reshape((4, -1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  4,  9],
       [16, 25, 36]])

In [57]:
a = np.arange(10)

In [58]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
a+=5

In [60]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
print(np.arange(3, 20, 3))

[ 3  6  9 12 15 18]


In [62]:
np.random.shuffle(a)

In [63]:
a

array([ 8,  9, 10,  5,  7, 12,  6, 14, 11, 13])

In [64]:
a = np.random.rand(2, 3)

In [65]:
a

array([[0.51764063, 0.68558583, 0.76926395],
       [0.21328394, 0.44908889, 0.89194063]])

In [66]:
a = np.random.randn(3, 2)

In [67]:
a

array([[ 1.07034596, -0.19286696],
       [ 2.71558703,  0.86381144],
       [ 0.11478893,  0.57320379]])

In [68]:
a = np.random.randint(5, 10, 3)

In [69]:
a

array([6, 6, 9])

In [70]:
np.random.randint(5, 100, (5, 5))

array([[ 7, 52, 60, 57, 17],
       [25,  5, 68, 87, 58],
       [21, 78, 85, 68, 93],
       [10, 72, 26, 29, 26],
       [27, 25, 21, 33, 35]])

In [71]:
arr = np.array([1,2,3,4,5,6,7])

In [72]:
element = np.random.choice(arr)

In [73]:
element

7

In [74]:
a = np.array([[1,2,3,4.0], 
              [7, 8, 9, 10]])

In [75]:
np.min(a, axis = 0)

array([1., 2., 3., 4.])

In [76]:
np.min(a, axis = 1)

array([1., 7.])

In [77]:
a

array([[ 1.,  2.,  3.,  4.],
       [ 7.,  8.,  9., 10.]])

In [78]:
b = np.array([1,2,3,4,5])

In [79]:
b

array([1, 2, 3, 4, 5])

In [80]:
m = sum(b)/5

In [81]:
print(m)

3.0


In [82]:
m = np.mean(b)

In [83]:
m

3.0

In [84]:
m = np.mean(a, axis = 0)

In [85]:
m

array([4., 5., 6., 7.])

In [86]:
m = np.mean(a, axis=1)
print(m)

[2.5 8.5]


In [87]:
print(np.median(a))

5.5


In [88]:
c = np.arange(8)+1

In [89]:
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [90]:
w = np.array([1,2,3,4,5,4,3,2])

In [91]:
np.average(c, weights=w)

4.833333333333333

In [92]:
print(np.mean(c))

4.5


In [93]:
c.dot(w)/sum(w)

4.833333333333333

In [94]:
u = np.mean(c)
std_dev = np.sqrt(np.mean(abs(c - u)**2))

In [95]:
std_dev

2.29128784747792

In [96]:
std_dev = np.std(c)

In [97]:
std_dev

2.29128784747792

In [98]:
var = std_dev**2

In [99]:
var

5.25

In [100]:
print(np.var(c))

5.25
