In [1]:
import pandas as pd
import numpy as np

In [2]:
user_data = {
    'Marks_A':np.random.randint(50, 100, 5),
    'Marks_B':np.random.randint(50, 100, 5),
    'Marks_C':np.random.randint(50, 100, 5)
}

In [3]:
type(user_data)

dict

In [4]:
df = pd.DataFrame(user_data, dtype='float64')

In [6]:
print(df, type(df))

   Marks_A  Marks_B  Marks_C
0     86.0     85.0     96.0
1     86.0     83.0     64.0
2     69.0     93.0     54.0
3     52.0     83.0     98.0
4     59.0     90.0     82.0 <class 'pandas.core.frame.DataFrame'>


In [8]:
df.head(n = 2)

Marks_A  Marks_B  Marks_C
0     86.0     85.0     96.0
1     86.0     83.0     64.0

In [9]:
df

Marks_A  Marks_B  Marks_C
0     86.0     85.0     96.0
1     86.0     83.0     64.0
2     69.0     93.0     54.0
3     52.0     83.0     98.0
4     59.0     90.0     82.0

In [10]:
df.columns

Index(['Marks_A', 'Marks_B', 'Marks_C'], dtype='object')

In [11]:
df_ = df.to_csv('marks.csv')

In [12]:
my_data = pd.read_csv('marks.csv')

In [13]:
my_data

Unnamed: 0  Marks_A  Marks_B  Marks_C
0           0     86.0     85.0     96.0
1           1     86.0     83.0     64.0
2           2     69.0     93.0     54.0
3           3     52.0     83.0     98.0
4           4     59.0     90.0     82.0

In [14]:
my_data = my_data.drop(columns=['Unnamed: 0'])

In [15]:
my_data

Marks_A  Marks_B  Marks_C
0     86.0     85.0     96.0
1     86.0     83.0     64.0
2     69.0     93.0     54.0
3     52.0     83.0     98.0
4     59.0     90.0     82.0

In [16]:
my_data.describe()

Marks_A    Marks_B    Marks_C
count   5.000000   5.000000   5.000000
mean   70.400000  86.800000  78.800000
std    15.469324   4.494441  19.421637
min    52.000000  83.000000  54.000000
25%    59.000000  83.000000  64.000000
50%    69.000000  85.000000  82.000000
75%    86.000000  90.000000  96.000000
max    86.000000  93.000000  98.000000

In [17]:
sub_data = my_data.iloc[:2, ]

In [18]:
sub_data

Marks_A  Marks_B  Marks_C
0     86.0     85.0     96.0
1     86.0     83.0     64.0

In [19]:
my_data.iloc?

In [20]:
idx = my_data.columns.get_loc('Marks_A')

In [21]:
idx

0

In [22]:
idx = my_data.columns.get_loc('Marks_C')

In [23]:
idx

2

In [24]:
idx = [my_data.columns.get_loc('Marks_A'), my_data.columns.get_loc('Marks_C')]

In [25]:
idx

[0, 2]

In [26]:
my_data.iloc[3, idx]

Marks_A    52.0
Marks_C    98.0
Name: 3, dtype: float64

In [27]:
my_data

Marks_A  Marks_B  Marks_C
0     86.0     85.0     96.0
1     86.0     83.0     64.0
2     69.0     93.0     54.0
3     52.0     83.0     98.0
4     59.0     90.0     82.0

In [28]:
my_data.sort_values(by = ['Marks_B', 'Marks_A'], ascending=True)

Marks_A  Marks_B  Marks_C
3     52.0     83.0     98.0
1     86.0     83.0     64.0
0     86.0     85.0     96.0
4     59.0     90.0     82.0
2     69.0     93.0     54.0

In [29]:
my_data.sort_values?

In [30]:
type(my_data)

pandas.core.frame.DataFrame

In [31]:
data = my_data.values

In [32]:
print(data, type(data))

[[86. 85. 96.]
 [86. 83. 64.]
 [69. 93. 54.]
 [52. 83. 98.]
 [59. 90. 82.]] <class 'numpy.ndarray'>


In [33]:
new_data = pd.DataFrame(data, dtype='int32', columns=['Marks_A', 'Marks_B', "Marks_C"])

In [34]:
new_data

Marks_A  Marks_B  Marks_C
0       86       85       96
1       86       83       64
2       69       93       54
3       52       83       98
4       59       90       82